# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c66a0f825f3df1b67a8500e7d942cea4"
name = "DC Decimal Discounts"
handle = "dc-decimal-discounts-lyniew"
application_url = "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/"
embedded = true

[build]
dev_store_url = "furmanek.myshopify.com"
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_discounts"

[auth]
redirect_urls = [
  "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/auth/callback",
  "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/auth/shopify/callback",
  "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/api/auth/callback"
]

[pos]
embedded = false
