# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c436a8cc5bb4ce40e5b6a3b8ff5feeb1"
name = "DC Decimal Disocunts"
handle = "dc-decimal-discounts"
application_url = "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/webhook"

  [[webhooks.subscriptions]]
  topics = ["shop/update"]
  uri = "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/webhook"

  [[webhooks.subscriptions]]
  topics = ["products/update"]
  uri = "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/webhook"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_discounts,write_discounts"

[auth]
redirect_urls = [
  "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/auth/callback",
  "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/auth/shopify/callback",
  "https://dc-decimal-discounts.jakub-okseniuk.workers.dev/api/auth/callback"
]

[pos]
embedded = false
